---

- !pacman
  name: Install bluetooth daemon
  package: "{{ item }}"
  with:
    items:
      - bluez
      - bluez-utils

- !pacman
  name: Install bluetooth manager
  package: blueman

- !sd_service
  name: Activate bluetooth
  service: bluetooth
  started: true
  enabled: true
